### ISSUE TITLE
ERROR DECODING

### ISSUE THREAD

**Issue by ReoGentO** [MasterDevX/XCoder#37]
[02.05.2022 18:18:47] Получена ошибка: 
Traceback (most recent call last):
  File "C:\Users\user\Desktop\XCoder_v2.0.1-prerelease\Main.py", line 73, in sc_decode
    decompileSC(f"{folder}{file}", CurrentSubPath, folder = folder, folder_export = folder_export)
  File "C:\Users\user\Desktop\XCoder_v2.0.1-prerelease\system\Lib.py", line 363, in decompileSC
    img.save(f"{folder_export}{CurrentSubPath}{baseName}.png")
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", line 2300, in save
    save_handler(self, fp, filename)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\PngImagePlugin.py", line 1374, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\ImageFile.py", line 510, in _save
    encoder.setimage(im.im, b)
SystemError: tile cannot extend outside image

How to fix it

**Comment by Pikn1K** [comment]
@ReoGentO how u fix problem?
