### ISSUE TITLE
ERROR! (builtins.NotADirectoryError: [WinError 267] Неверно задано имя папки: './In-Decompressed-SC/loading_tex.png/')

### ISSUE THREAD

**Issue by IvanSCP** [MasterDevX/XCoder#44]
```
Traceback (most recent call last):
  File "C:\Users\*****\Desktop\XCoder-master\Main.py", line 88, in sc_encode
    compileSC(f"{folder}{i}/", folder_export=folder_export)
  File "C:\Users\*****\Desktop\XCoder-master\system\Lib.py", line 376, in compileSC
    [files.append(i) if i.endswith(".png") else None for i in os.listdir(_dir)]
NotADirectoryError: [WinError 267] Неверно задано имя папки: './In-Decompressed-SC/loading_tex.png/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\*****\Desktop\XCoder-master\Main.py", line 200, in <module>
    sc_encode()
  File "C:\Users\*****\Desktop\XCoder-master\Main.py", line 92, in sc_encode
    write_log(traceback.format_exc())
  File "C:\Users\*****\Desktop\XCoder-master\system\Lib.py", line 82, in write_log
    log.write(string.got_error % (time.strftime('%d.%m.%Y %H:%M:%S'), err))
TypeError: not all arguments converted during string formatting
```
idk how to fix it

**Comment by roccociro55** [comment]
Create a folder in IN DECOMPRESSED SC then paste in the folder your PNGS.
